import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Time Sheet Managment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased `}
      >
        {/* Header =------------------ */}
        <section className=" w-full">

          <Navbar />

        </section>
        {/* Header =------------------ */}

        <div className="fixed flex items-center justify-between w-screen h-screen">
          <div className="w-[5%] h-full">
            <Sidebar />
          </div>
          <div className="w-[95%] px-12 pt-12 bg-[#F0F0F2] h-full">
            {children}
          </div>

        </div>
      </body>
    </html>
  );
}
